### PR TITLE
add prusa rambo

### PR DESCRIPTION
**Pull request by bgiot**
Add support for building prusa firmwares

### CODE REVIEW

**Comment by bgiot** [comment]
@ivankravets  @valeros  @rafacouto @johnduhart  any news ?

**Review by ivankravets — CHANGES_REQUESTED** [review]
Thanks for the PR! We need the next files:
- Libraries -> https://github.com/platformio/platformio-pkg-framework-arduinoavr/tree/master/libraries/__cores__
- Variant -> https://github.com/platformio/platformio-pkg-framework-arduinoavr/tree/master/variants

**Comment by bgiot** [comment]
As defined in the prusa_rambo.json (see PR https://github.com/platformio/platform-atmelavr/pull/163), we use the default variant for rambo, and the existing arduino __cores__.  is it an issue ?

**Comment by ivankravets** [comment]
I see, what to do with libraries? Where is the source code of this core?

**Comment by bgiot** [comment]
Sorry, I don't think I understand your question... when building the Prusa Firmware, I use this:
platform = atmelavr
board = prusa_rambo
framework = arduino
You can check my platformio.ini at https://github.com/bgiot/Prusa-Firmware/blob/BMGCustom/platformio.ini

**Comment by ivankravets** [comment]
Where did get source code for this prusa_rambo core?

**Comment by bgiot** [comment]
from Prusa github: https://github.com/prusa3d/Arduino_Boards
The only modification from reprap_rambo is in the wiring.c file I think.

**Comment by bgiot** [comment]
Maybe I can explain the all story, so you understand why my PR.
Up to version 3.7.x of the Prusa 3D printer firmware, I was able to compile it with platform.io with the following config:
platform = atmelavr
board = reprap_rambo
framework = arduino
With the up-coming 3.8 versions, there is an issue because Prusa has modified one of the TIMER0, and we have a conflict with the one defined by arduino core.  
so I did the minimal changes in platform.io packages/platforms to be able to compile the new firmware.  This implies a new board definition and a new 'core' that I called 'prusa_rambo'.

**Comment by bgiot** [comment]
Thank you. Will test.

**Comment by bgiot** [comment]
Successful test with platform upstream (https://github.com/platformio/platform-atmelavr.git)

**Pull request merged**
