### PR TITLE
Support for a dwengo board

### PR DESCRIPTION
**Pull request by itkovian**
See http://www.dwengo.org for an overview of the product and http://www.dwengo.org/sites/default/files/Dwenguino.zip for the original source code (version 2.1.0).

### CODE REVIEW

**Comment by ivankravets** [comment]
Please move core's related libraries to https://github.com/platformio/platformio-pkg-framework-arduinoavr/tree/master/libraries/__cores__

PIO Build System will load them automatically from that location.

**Comment by itkovian** [comment]
You mean what is now under libraries/Dwenguino, right?

**Comment by ivankravets** [comment]
Yes, you are right. You even can copy all Dwenguino's libraries to https://github.com/platformio/platformio-pkg-framework-arduinoavr/tree/master/libraries/__cores__/dwenguino

**Comment by ivankravets** [comment]
Please sorry, but `core` should have the same name withon `__cores__` directory. Please replace `Dwenguino` by `dwenguino`.

Thanks!

**Comment by itkovian** [comment]
Do you have pointers to how I can actually test this works?

**Comment by ivankravets** [comment]
Sure, just place this modified package to `~/.platformio/packages/package-frameworkarduinoavr` and custom board to `~/.platformio/platforms/atmelavr/boards`

**Pull request closed without merging**
